# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WorktreeManagerCli < Formula
  desc "Worktree Manager — orchestrate git worktrees, AI agents, and team workflows"
  homepage "https://github.com/LucasPcq/worktree-manager-cli"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/LucasPcq/worktree-manager-cli/releases/download/v0.1.0/worktree-manager-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "76fb778666c5391c0205cb8591cc062e28e7bc20190452baf716d8f9ee91e664"

      define_method(:install) do
        bin.install "wtm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/LucasPcq/worktree-manager-cli/releases/download/v0.1.0/worktree-manager-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "7e8673526e33d8c34fda4193a44c2ece35a00e9709b4e60d303921fd9a475657"

      define_method(:install) do
        bin.install "wtm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/LucasPcq/worktree-manager-cli/releases/download/v0.1.0/worktree-manager-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "a3c192ce01a090db7a036d197f0b169c612732c4db5b7f1f1515f5b509ed15f5"
      define_method(:install) do
        bin.install "wtm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/LucasPcq/worktree-manager-cli/releases/download/v0.1.0/worktree-manager-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "79289beeb0411103221e15c7ea7db42543c4cb70d6c75da2dcd1e57a999ef5ff"
      define_method(:install) do
        bin.install "wtm"
      end
    end
  end
end
