# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wtm < Formula
  desc "Worktree Manager — orchestrate git worktrees, AI agents, and team workflows"
  homepage "https://github.com/LucasPcq/worktree-manager-cli"
  version "0.14.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/LucasPcq/worktree-manager-cli/releases/download/v0.14.0/worktree-manager-cli_0.14.0_darwin_amd64.tar.gz"
      sha256 "cbeefc13d15d69cc31411f8e7985ebf662edf6df86a24684401b97476503195f"

      define_method(:install) do
        bin.install "wtm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/LucasPcq/worktree-manager-cli/releases/download/v0.14.0/worktree-manager-cli_0.14.0_darwin_arm64.tar.gz"
      sha256 "7ae9b98ed4abf9c2aeb105da1004a26542f5cf63ce4360d058a1e1b761f58eb3"

      define_method(:install) do
        bin.install "wtm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/LucasPcq/worktree-manager-cli/releases/download/v0.14.0/worktree-manager-cli_0.14.0_linux_amd64.tar.gz"
      sha256 "6352997f06055b5fa3388e826e0c74ab6a11f07eafd0cb3628e006d20ef219a5"
      define_method(:install) do
        bin.install "wtm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/LucasPcq/worktree-manager-cli/releases/download/v0.14.0/worktree-manager-cli_0.14.0_linux_arm64.tar.gz"
      sha256 "0fd720e75fc025d0ebe0d75515ab0641fecbf419c969da55d09ae1c8b4fe6df4"
      define_method(:install) do
        bin.install "wtm"
      end
    end
  end
end
