# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wtm < Formula
  desc "Worktree Manager — orchestrate git worktrees, AI agents, and team workflows"
  homepage "https://github.com/LucasPcq/wtm"
  version "0.28.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/LucasPcq/wtm/releases/download/v0.28.0/wtm_0.28.0_darwin_amd64.tar.gz"
      sha256 "7963d4bc2024911658a0d7686f83dc521fcd8a396fdfc74a4b32dc2ddca5a979"

      define_method(:install) do
        bin.install "wtm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/LucasPcq/wtm/releases/download/v0.28.0/wtm_0.28.0_darwin_arm64.tar.gz"
      sha256 "114c3e51d764936db9207afadff2b5294729e227286ef3d78a18f918e7e1cdf5"

      define_method(:install) do
        bin.install "wtm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/LucasPcq/wtm/releases/download/v0.28.0/wtm_0.28.0_linux_amd64.tar.gz"
      sha256 "800e6aafec95f58de2c16183d734df774b248ce71fea37ddac88cde5752313eb"
      define_method(:install) do
        bin.install "wtm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/LucasPcq/wtm/releases/download/v0.28.0/wtm_0.28.0_linux_arm64.tar.gz"
      sha256 "a59d56b2a98008f326b6d7d3cc26566e3afbd84ad06d4806b4e6116a51a2612b"
      define_method(:install) do
        bin.install "wtm"
      end
    end
  end
end
